# Generated by Django 3.2.10 on 2021-12-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialauth',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='usersocialauth',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usersocialauth',
            name='profile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='usersocialauth',
            name='screen_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
