# Generated by Django 3.2.10 on 2021-12-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211211_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialauth',
            name='screen_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
