# Generated by Django 3.2.10 on 2021-12-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_usersocialauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersocialauth',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='usersocialauth',
            name='profile_url',
        ),
        migrations.RemoveField(
            model_name='usersocialauth',
            name='screen_name',
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
