# Generated by Django 3.2.10 on 2021-12-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_userprofile_project_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
    ]
