# Generated by Django 3.2.10 on 2021-12-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectsdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('stage', models.CharField(max_length=100)),
                ('prog_lang', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=1)),
                ('count', models.IntegerField()),
                ('framework', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
            ],
        ),
    ]
