# Generated by Django 3.2.10 on 2021-12-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_projectsdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsdetails',
            old_name='prog_lang',
            new_name='prog',
        ),
    ]
