# Generated by Django 3.2.10 on 2021-12-12 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_projectstaken'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsdetails',
            name='creator',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsdetails',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
