# Generated by Django 3.2.10 on 2021-12-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211212_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstaken',
            name='project',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectstaken',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
